language: cpp
compiler: gcc
sudo: require
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt593base'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt5-qmake qtbase5-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt5'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt5'


script:
  - cd test
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  
after_success:
  - ./release/test
  
